config/routes.rb
Rails.application.routes.draw do

  resources :payments

  get 'home/index'
  root 'home#index'

  resources :items do
    member do
      get :add_to_cart
      delete :remove_from_cart
    end
  end

  resources :carts do
    member do
      get :checkout
      get :confirm_checkout
    end
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  INCOMPLETE = 'incomplete'   # Initial state
  PAID = 'paid'         # Cart turned into confirmed order after successful payment

  has_many :items
  belongs_to :payment

  # scope :open, -> { joins("join payments on payments.id = carts.payment_id").where("payments.state = ? ", Payment::INCOMPLETE) }
  scope :open, -> { joins("join payments on payments.id = carts.payment_id").where("carts.state = ? ", INCOMPLETE) }

  def self.mine
    Cart.order("id desc").where(payment_id: nil).first || Cart.order("id desc").open.first || Cart.create
  end

  def price
    items.pluck(:price).sum
  end

  def price_in_cents
    (price * 100).to_i
  end

  def state_paid
    update(state: PAID)
  end

end

app/models/item.rb
class Item < ActiveRecord::Base

  validates :price, :name, presence: true

	# def self.total_price
	# 	sum(:price)
	# end

  def price_in_cents
    (price * 100).to_i
  end

private

end

app/models/payment.rb
class Payment < ActiveRecord::Base

  has_one :cart

  INCOMPLETE = 'incomplete'   # Initial state
  SUCCESS = 'success'         # Payment wa successful
  # CANCELLED = 'cancelled'     # User chose not to confirm payment in final step.
  FAILED = 'failed'     # User chose not to confirm payment in final step.

  scope :incomplete, -> { where(state: INCOMPLETE) }
  scope :success, -> { where(state: SUCCESS) }
  # scope :cancelled, -> { where(state: CANCELLED) }
  scope :failed, -> { where(state: FAILED) }
  scope :paypal_pending, -> { where(paypal_status: "Pending") }
  scope :paypal_completed, -> { where(paypal_status: "Completed") }

  attr_reader :sucess, :result_message

  def purchase
    response = EXPRESS_GATEWAY.purchase(cart.price_in_cents, express_purchase_options)
    # cart.update_attribute(:purchased_at, Time.now) if response.success?
    update(paypal_fee: response.params["fee_amount"], 
      paypal_status: response.params["PaymentInfo"]["PaymentStatus"],
      paypal_transaction_id: response.params["transaction_id"],
      state: response.success? ? SUCCESS : FAILED)
    cart.state_paid if response.success?
    @result_message = response.success? ? 'Your payment has been received, thank you!' : response.message
    @success = response.success?
  end

  def express_token=(token)
    self[:express_token] = token
    if new_record? && !token.blank?
      # you can dump details var if you need more info from buyer
      details = EXPRESS_GATEWAY.details_for(token)
      self.express_payer_id = details.payer_id
    end
  end

  private

  def express_purchase_options
    {
      :ip => ip,
      :token => express_token,
      :payer_id => express_payer_id
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :update, :destroy, :checkout, :confirm_checkout]

  def index
    @carts = Cart.all
  end

  def show
  end

  def new
    @cart = Cart.new
  end

  def edit
    @cart = Cart.find_by(id: params[:id]) || Cart.mine
  end

  def create
    @cart = Cart.create(cart_params)
    if @cart.valid?
      redirect_to carts_url, notice: 'Cart was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        redirect_to carts_url, notice: 'Cart was successfully updated.'
      else
        render :edit
      end
    end
  end

  def destroy
    @cart.destroy
    redirect_to carts_url, notice: 'Cart was successfully destroyed.'
  end

  def checkout
    response = EXPRESS_GATEWAY.setup_purchase(@cart.price_in_cents,
      ip: request.remote_ip,
      return_url: confirm_checkout_cart_url(@cart),
      cancel_return_url: edit_cart_url(@cart),
      currency: "AUD",
      allow_guest_checkout: true,
      items: paypal_items)
    if response.token.nil?
      # The setup failed, check response.message
      flash.alert = response.message
      render 'edit'
    else
      redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
    end
  end

  def confirm_checkout
    details = EXPRESS_GATEWAY.details_for(params[:token])
    @payment = @cart.payment || Payment.create(express_token: params[:token],
        first_name: details.params["first_name"],
        last_name: details.params["last_name"],
        amount: details.params["order_total"].to_f,
        address: details.params["street1"])
    @cart.update(payment: @payment) if @cart.payment.nil?
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.fetch(:cart, {})
  end

  def paypal_items
    @cart.items.each_with_object([]) do |item, a|
      a << { name: item.name, description: item.name, quantity: 1, amount: item.price_in_cents }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:show, :edit, :update, :destroy, :add_to_cart, :remove_from_cart]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to items_path, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: 'Item was successfully destroyed.'
  end

  def add_to_cart
    cart = Cart.mine
    cart.items << @item
    redirect_to edit_cart_path(cart)
  end

  def remove_from_cart
    cart = Cart.mine
    cart.items = cart.items - [@item]
    cart.save
    redirect_to edit_cart_path(cart)
  end

private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :price)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  def index
    @payments = Payment.all
  end

  def show
    # byebug
    @paypal_details = EXPRESS_GATEWAY.transaction_details(@payment.paypal_transaction_id).params rescue nil
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
    @payment.update(payment_params)
    @payment.purchase
end

  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_payment
      @payment = Payment.find(params[:id])
    end

    def payment_params
      params.require(:payment).permit(:ip, :express_token, :express_payer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def spinner_with_text
    "<i class='fa fa-spinner fa-spin'></i> #{I18n.t('titles.loading')}".html_safe
  end

  def spinner
    "<i class='fa fa-spinner fa-spin'></i>"
  end

  def text_only
    I18n.t('titles.loading') + "..."
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/carts/_form.html.erb
<div class='row'>
  <div class='col-lg-4'>
    <% if @cart.items.empty? %>
      <h4>Nothing in cart.</h4>
    <% else %>
      <h4>Cart contents</h4>
    <% end %>
    <table class='table'>
      <tr>
        <th>Product</th>
        <td>Price</td>
      </tr>
      <% @cart.items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= number_to_currency(item.price) %></td>
          <%= render partial: 'shared/actions', locals: { edit_url: nil, destroy_url: remove_from_cart_item_path(item) } %>
        </tr>
      <% end %>
      <tr>
        <th>Total</th>
        <th><%= number_to_currency(@cart.price) %>
      </tr>
    </table>
    <br />
    <% unless @cart.items.empty? %>
      <%= link_to image_tag("/uploads/images/paypal_express_checkout.gif"), checkout_cart_path(@cart), data: { disable_with: spinner } %>
    <% end %>
  </div>
  <div class='col-lg-4'>
    <h4>Available products</h4>
    <%= render partial: 'items/index', locals: { items: Item.order(:name), actions: false } %>
  </div>
</div>

app/views/carts/confirm_checkout.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <h3 class='well'>Review & submit order</h3>
    <%= render 'payments/form' %>
  </div>
</div>

app/views/carts/edit.html.erb
<h2 class='well'>My cart</h2>
<%= render 'form' %>

app/views/carts/index.html.erb
<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/home/index.html.erb
<h2 class='well'>Paypal test bed application</h2>

app/views/items/_form.html.erb
<%= simple_form_for @item, defaults: { label_html: { style: 'width: 200px;' }, input_html: {style: 'width: 400px;' } } do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :price %>
  <div class="actions">
    <%= f.submit "Save", class: 'btn btn-primary' %>
    <%= link_to 'Cancel', items_path, class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/items/_index.html.erb
<table class='table'>
  <tr>
    <th>Product</th>
    <th>Price</th>
    <th></th>
  </tr>

  <% items.each do |item| %>
    <tr>
      <td><%= item.name %></td>
      <td><%= number_to_currency(item.price) %></td>
      <% if actions %>
        <%= render partial: 'shared/actions', locals: { model_class: Item, edit_url: edit_item_path(item), destroy_url: item_path(item) } %>
      <% end %>
      <td>
        <%= link_to add_to_cart_item_path(item), title: 'Add to cart' do %>
          <i class='fa fa-shopping-cart' style='color: green;'></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/items/edit.html.erb
<h2 class='well'>Edit product</h2>

<%= render 'form' %>

app/views/items/index.html.erb
<h2 class='well'>Products</h2>
<%= link_to 'New Item', new_item_path, class: 'pull-right btn btn-primary' %>

<div class='row'>
  <div class='col-lg-6'>
    <%= render partial: 'items/index', locals: { items: @items, actions: true } %>
  </div>
</div>

app/views/items/new.html.erb
<h2 class='well'>New product</h2>

<%= render 'form' %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_admin_menu_link.html.erb
<li>
  <%= link_to path do %>
    <i class="fa <%= icon %>"></i> <%= label %>
  <% end %>
</li>

app/views/layouts/_html_head.html.erb
<head>

  <!-- Typekit fo ts -->
  <!--
  <script src="https://use.typekit.net/yzd7hhb.js"></script>
  <script>try{Typekit.load({ async: true });}catch(e){}</script>
  -->

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>'Payl Test App'</title>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag :application %>

  <!-- Google Maps -->

  <%= csrf_meta_tags %>

</head>

app/views/layouts/_menu.html.erb
<style>
  li .separated {
    border-top: solid 1px #aaa;
  }
</style>

<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" style='border-width: 0'>
  <div class="navbar-header">
    <div class="collapse navbar-collapse" id="collapse-main-menu">
      <ul class="nav navbar-nav top-menu" style='width: 100%'>
        <%= render partial: 'layouts/admin_menu_link', locals: { path: root_path, label: 'Home', icon: 'fa-home' } %>
        <%= render partial: 'layouts/admin_menu_link', locals: { path: items_path, label: 'Products', icon: 'fa-list' } %>
        <%= render partial: 'layouts/admin_menu_link', locals: { path: payments_path, label:  'Payments', icon: 'fa-indent' } %>
        <%= render partial: 'layouts/admin_menu_link', locals: { path: edit_cart_path(Cart.mine), label: 'My Cart', icon: 'fa-indent' } %>
      </ul>
    </div>
  </div>
</nav>

<script>
  $('.dropdown-toggle').dropdown()
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <%= render 'layouts/html_head' %>

  <body>
    <div id='wrap'>
      <div class="container" style=' background-color: white; padding-right: 1%'>
        <div class="col-lg-12" style='margin-top: 70px;'>
          <%= render 'layouts/menu' %>
          <%= bootstrap_flash %>
        </div>
        <div class='row'>
          <div class="col-lg-12">
            <%= yield %>
          </div><!--/col-->
        </div>
      </div>
    </div>

  </body>
</html>

app/views/payments/_form.html.erb
<%= simple_form_for @payment, defaults: { label_html: { style: 'width: 200px;' }, input_html: {style: 'width: 400px;' } } do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <p><%= f.input :first_name %></p>
    <p><%= f.input :last_name %></p>
    <p><%= f.input :address %></p>
    <p><%= f.input :amount, as: :currency %></p>
  <div class="field">
    <%= f.hidden_field :ip %>
  </div>
  <div class="field">
    <%= f.hidden_field :express_token, value: params[:token] %>
  </div>
  <div class="field">
    <%= f.hidden_field :express_payer_id, value: params[:PayerID] %>
  </div>
  <div class="actions">
    <%= f.submit "Confirm payment", class: 'btn btn-primary' %>
    <%= link_to 'Cancel', edit_cart_path(@payment.cart), class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/payments/create.html.erb
<h3><%= @payment.result_message %></h3>
<br />
<%= link_to "Back to cart", edit_cart_path(Cart.mine), class: 'btn btn-primary' %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<style>

  a.payment {
    color: #27f !important;
  }
  a.payment:hover {
    color: #00b !important;
    background-color: transparent;
  }
</style>

<h2 class='well'>Paypal payments</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Paypal ref.</th>
      <th>Paid at</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>Status</th>
      <th>Amount</th>
      <th>Paypal fee</th>
      <th>Paypal status</th>
      <th>Fee breakdown</th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= link_to(payment.paypal_transaction_id, payment, class: 'payment', data: {disable_with: spinner }) %></td>
        <td><%= payment.created_at.localtime.strftime("%d-%m-%y %H:%M") %></td>
        <td><%= payment.first_name %></td>
        <td><%= payment.last_name %></td>
        <td><%= payment.address %></td>
        <td><%= payment.state %></td>
        <td><%= number_to_currency(payment.amount.to_f) %></td>
        <td><%= number_to_currency(payment.paypal_fee.to_f) %></td>
        <td><%= payment.paypal_status %></td>
        <td>
          <% unless payment.paypal_fee.nil? %>
            30cts + <%= ((payment.paypal_fee - 0.30) / payment.amount * 100).round(2) %>%
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/payments/show.html.erb
<h2 class='well'>Paypal transaction details for transaction id <%= @payment.paypal_transaction_id %></h2>


<% if @paypal_details.nil? %>
  <h2>No details received from payal</h2>
<% else %>
  <% @paypal_details %>
  <div class='row'>
    <div class='col-lg-6'>
      <table class='table'>
        <tr style='font-size: 1.5em;'>
          <th>Paypal field</th>
          <th>Value</th>
        </tr>
        <tr><th>result</th><td><%= @paypal_details['ack'] %></td></tr>
          <tr><th>payer</th><td><%= @paypal_details["payer"] %></td></tr>
          <tr><th>payer_id</th><td><%= @paypal_details["payer_id"] %></td></tr>
          <tr><th>payer_status</th><td><%= @paypal_details["payer_status"] %></td></tr>
          <tr><th>first_name</th><td><%= @paypal_details["first_name"] %></td></tr>
          <tr><th>last_name</th><td><%= @paypal_details["last_name"] %></td></tr>
          <tr><th>street1</th><td><%= @paypal_details["street1"] %></td></tr>
          <tr><th>city_name</th><td><%= @paypal_details["city_name"] %></td></tr>
          <tr><th>state_or_province</th><td><%= @paypal_details["state_or_province"] %></td></tr>
          <tr><th>country</th><td><%= @paypal_details["country"] %></td></tr>
          <tr><th>country_name</th><td><%= @paypal_details["country_name"] %></td></tr>
        </table>
      </div>
      <div class='col-lg-6'>
        <table class='table'>
          <tr style='font-size: 1.5em;'>
            <th>Paypal field</th>
            <th>Value</th>
          </tr>
          <tr><th>postal_code</th><td><%= @paypal_details["postal_code"] %></td></tr>
          <tr><th>payment_date</th><td><%= @paypal_details["payment_date"] %></td></tr>
          <tr><th>gross_amount</th><td><%= @paypal_details["gross_amount"] %></td></tr>
          <tr><th>gross_amount_currency_id</th><td><%= @paypal_details["gross_amount_currency_id"] %></td></tr>
          <tr><th>fee_amount</th><td><%= @paypal_details["fee_amount"] %></td></tr>
          <tr><th>fee_amount_currency_id</th><td><%= @paypal_details["fee_amount_currency_id"] %></td></tr>
          <tr><th>exchange_rate"</th><td><%= @paypal_details["exchange_rate"] %></td></tr>
          <tr><th>payment_status</th><td><%= @paypal_details["payment_status"] %></td></tr>
          <tr><th>pending_reason</th><td><%= @paypal_details["pending_reason"] %></td></tr>
          <tr><th>quantity</th><td><%= @paypal_details["quantity"] %></td></tr>
        <tr>
      </table>
    </div>
  </div>
<% end %>

app/views/payments/update.html.erb
<h3><%= @payment.result_message %></h3>
<br />
<%= link_to "Back to cart", edit_cart_path(Cart.mine), class: 'btn btn-primary' %>

app/views/shared/_actions.html.erb
<% view_url ||= nil %>
<% destroy_url ||= nil %>
<% min_width = view_url.nil? ? 42 : 58 %>
<% no_turbolink ||= false %>

<% confirm_prompt ||= I18n.t('prompts.confirm') %>

<td style='min-width: <%= min_width %>px;'>
  <% if view_url %>
    <%= link_to view_url, html_options = { title: I18n.t('actions.preview'), data: { disable_with: spinner } } do %>
      <i class='fa fa-binoculars blue-link-fg' title='<%=  I18n.t('actions.preview') %>' style='color: #428bca'></i>
    <% end %>
  <% end %>
  <% if edit_url %>
    <%= link_to edit_url, html_options = { color: '#000', title: I18n.t('actions.edit', model: model_class.to_s), data: { disable_with: spinner }  } do %>
      <i class='fa fa-edit blue-link-fg' title='<%= I18n.t("actions.edit", model: model_class.to_s) %>' style='color: #428bca'></i>
    <% end %>
  <% end %>
  <% if destroy_url %>
    <%= link_to destroy_url, method: :delete, title: I18n.t('actions.delete'), data: { confirm: confirm_prompt } do %>
      <i class='fa fa-close red-fg' title='<%= I18n.t('actions.delete') %>' style='color: red'></i>
    <% end %>
  <% end %>
</td>